title: Marc Van Uffelen
description: The online resume (CV) of me (Marc Van Uffelen). I mainly created this to make myself more visible to everyone online.
url: "https://marcswebsite.github.io"
theme: jekyll-theme-minimal

profile_picture: assets/MarcWebpagePic.png
